### ISSUE TITLE
Audio clipping issue

### ISSUE THREAD

**Issue by ghost** [cloudofoz/raylib-media#4]
Hello, I'm having an issue with the audio clipping pretty badly. I'm currently using Raylib 5.0, not sure if that might have something to do with it. I ran the unmodified (just changed the path to the video) first example code. Let me know if I can provide any more information.

https://github.com/user-attachments/assets/a914cd43-8988-4658-b635-646d92cdb48f

**Comment by cloudofoz** [comment]
Hi @sockentrocken ,

Thank you for reporting this issue! Let me explain how audio streaming is handled in **raylib-media**, as it will help clarify where the problem might lie:

1. **Audio packets** are processed and decoded into a circular buffer (**`A`**).
2. Each frame, if the **raylib AudioStream** is empty, a fixed chunk (**`B`**) of **`A`** is uploaded to the AudioStream (**`C`**), which has its own capacity.

The audio clipping you’re experiencing might be due to suboptimal sizes for these three buffers. To address this, you can try adjusting the capacities of **`A`**, **`B`**, and **`C`** early in your code (before calling `LoadMedia()`). Here’s how you can do that:

```c
// Adjust the capacity of the circular buffer (A):
SetMediaFlag(MEDIA_AUDIO_DECODED_BUFFER, [new_capacity]); // Default: 16 * 1024 bytes

// Set the size of the chunk (B) uploaded from A to the AudioStream each time it processes data:
// (Note: Since a callback isn't available, this size is fixed.)
SetMediaFlag(MEDIA_AUDIO_UPDATE, [new_capacity]); // Default: 4 * 1024 bytes

// Configure the size of the AudioStream buffer (C):
SetMediaFlag(MEDIA_AUDIO_STREAM_BUFFER, [new_capacity]); // Default: 1 * 1024 bytes
```

The default values are based on testing with my system, but they might need tuning for your setup. I recommend experimenting with these capacities to see if it resolves the clipping.

Additionally, please check your terminal output for any warnings or errors. These might provide more context about what’s causing the issue.

Let me know how it goes or if you need further assistance!

Best,

C.

---

![audio-packets](https://github.com/user-attachments/assets/d752749f-9932-4178-876e-c3e8ccfcd223)

**Comment by ghost** [comment]
Thank you, I fiddled with the values and fixed it.

```
// Adjust the capacity of the circular buffer (A):
SetMediaFlag(MEDIA_AUDIO_DECODED_BUFFER, 64 * 1024); // Default: 16 * 1024 bytes

// Set the size of the chunk (B) uploaded from A to the AudioStream each time it processes data:
// (Note: Since a callback isn't available, this size is fixed.)
SetMediaFlag(MEDIA_AUDIO_UPDATE, 16 * 1024); // Default: 4 * 1024 bytes

// Configure the size of the AudioStream buffer (C):
SetMediaFlag(MEDIA_AUDIO_STREAM_BUFFER, 4 * 1024); // Default: 1 * 1024 bytes
```

Anything lower than those values and I experience heavy clipping in my system. Thanks for the help again.

**Comment by cloudofoz** [comment]
Thank you for sharing the values that worked for your setup, this information will be helpful if other users encounter similar issues.
I'm glad to hear you resolved it!

**Comment by GuvaCode** [comment]
Yes. I've tried, but nothing has changed.
