### ISSUE TITLE
General choppiness when playing back video

### ISSUE THREAD

**Issue by ghost** [cloudofoz/raylib-media#6]
Hey, should've probably mentioned this with my first issue, as it was also happening then, but video playback is not very smooth at all, and I was wondering if maybe there's something I might have missed in configuring either RL-media or my system? Raysan had mentioned that H.264 video does not have this issue (or at least not as much as H.265), however I've tried both codecs to no avail. I've fiddled a bit with the MEDIA_VIDEO_QUEUE and MEDIA_VIDEO_MAX_DELAY flags, setting them both to very high and very low values, also to no effect. I'm at a bit of a loss on what should I do to optimize video playback. Thanks in advance.

**Comment by cloudofoz** [comment]
Hi @sockentrocken ,

Sorry to hear you’re still having playback issues. From what I recall, you successfully updated your FFmpeg libraries on Linux Mint 21.2 and compiled `raylib-media`.

In `raylib-media` (as used in the examples), video decoding and updating happen on the main thread along with rendering and other tasks. The only exception might be the raylib `AudioStream`, which may use a multithreaded library. Because of this, playback performance depends on how fast and stable your main loop runs. If your FPS is low or inconsistent, it can directly impact video playback smoothness.

Here are some steps you could try:

**Check your main loop’s FPS**: Since video playback depends on it, make sure your main loop runs smoothly at a stable and high FPS.

**Understand the limitations**: Professional media players likely decode a portion of the video ahead of time (buffering) and use separate threads for decoding. `raylib-media` keeps things simple by computing everything as needed, which could sometimes struggle with lower-end systems (or resource-heavy videos).

**Different video settings**: You could test with different videos or re-encode them at lower resolutions or with different codecs. Any FFmpeg codec supported in your Linux Mint setup should work. A lighter video file could help reduce system strain and improve playback.

Thank you for taking the time to test the library, and let me know how it goes!

**Comment by cloudofoz** [comment]
Hi @sockentrocken,

Since I haven’t heard back in a while, I’ll go ahead and close this issue for now. If you have more questions, feel free to reopen it or create a new issue!

Best,
C.
